### ISSUE TITLE
2#

### ISSUE THREAD

**Issue by MisterT81** [works-offline/logo#3]

**Comment by MisterT81** [comment]
@

**Comment by MisterT81** [comment]
[Blockchain Receive Payments API_ Accept Bitcoin Payments - Blockchain.pdf](https://github.com/works-offline/logo/files/4941241/Blockchain.Receive.Payments.API_.Accept.Bitcoin.Payments.-.Blockchain.pdf)

**Comment by MichalBryxi** [comment]
Spam? @remy ?

**Comment by remy** [comment]
@MichalBryxi thanks, you're right.

**Comment by remy** [comment]
Bot like. Suspect it'll be back, but have reported the content.
